# -*- coding: utf-8 -*-
"""LLM-TOS-CoT-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yry2AKEL4hrHNvgRROBuK_m0BPk2Qqj3
"""

# TOS_Deception_Detection_CoT_Experiment.ipynb

# Installation and Setup
"""
# TOS Deception Detection with Chain-of-Thought Prompting
## Research Experiment Implementation

### 1. Environment Setup
First, install the required packages:
"""

!pip install transformers bitsandbytes torch datasets scikit-learn pandas matplotlib seaborn tqdm accelerate


from huggingface_hub import login
login(new_session=False)

# Import Libraries
import torch
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from typing import List, Dict, Tuple
from tqdm import tqdm
import warnings
import os
warnings.filterwarnings('ignore')

from transformers import AutoModelForCausalLM, AutoTokenizer
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.metrics import classification_report

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

#Dataset Creation
"""
### 2. Dataset Creation
Creating a dataset with legitimate and deceptive TOS clauses
"""

class TOSDataset:
    def __init__(self):
        self.data = self.create_dataset()

    def create_dataset(self):
        """Create a balanced dataset of legitimate and deceptive TOS clauses"""

        # Legitimate clauses (based on privacy-respecting services)
        legitimate_clauses = [
            {
                "clause": "We will never sell your personal data to third parties.",
                "label": "legitimate",
                "source": "privacy-focused"
            },
            {
                "clause": "You can delete your account and all associated data at any time through your account settings.",
                "label": "legitimate",
                "source": "user-friendly"
            },
            {
                "clause": "We only collect data necessary for providing our service and will notify you of any changes to this policy.",
                "label": "legitimate",
                "source": "transparent"
            },
            {
                "clause": "Your data is encrypted both in transit and at rest using industry-standard encryption protocols.",
                "label": "legitimate",
                "source": "security-focused"
            },
            {
                "clause": "We will obtain your explicit consent before sharing any personal information with partners.",
                "label": "legitimate",
                "source": "consent-based"
            },
            {
                "clause": "You retain all rights to the content you upload and can export it at any time.",
                "label": "legitimate",
                "source": "user-rights"
            },
            {
                "clause": "We undergo regular third-party security audits and publish transparency reports annually.",
                "label": "legitimate",
                "source": "transparent"
            },
            {
                "clause": "Data retention is limited to 90 days after account deletion unless legally required otherwise.",
                "label": "legitimate",
                "source": "clear-retention"
            },
            {
                "clause": "You will be notified within 72 hours in case of any data breach affecting your account.",
                "label": "legitimate",
                "source": "breach-notification"
            },
            {
                "clause": "We do not use your data for advertising purposes without your explicit opt-in consent.",
                "label": "legitimate",
                "source": "no-ads"
            }
        ]

        # Deceptive clauses (dark patterns and privacy violations)
        deceptive_clauses = [
            {
                "clause": "By using our service, you grant us unlimited, irrevocable license to use your content for any purpose.",
                "label": "deceptive",
                "pattern": "rights-grab"
            },
            {
                "clause": "We may share your information with our affiliates and partners to enhance your experience.",
                "label": "deceptive",
                "pattern": "vague-sharing"
            },
            {
                "clause": "Account deletion requests will be processed, but some data may be retained indefinitely for our legitimate business purposes.",
                "label": "deceptive",
                "pattern": "fake-deletion"
            },
            {
                "clause": "We reserve the right to modify these terms at any time without notice, and continued use constitutes acceptance.",
                "label": "deceptive",
                "pattern": "silent-updates"
            },
            {
                "clause": "Your anonymized data may be used for research purposes and shared with academic institutions.",
                "label": "deceptive",
                "pattern": "pseudo-anonymous"
            },
            {
                "clause": "By clicking 'Accept', you agree to receive promotional materials from us and our carefully selected partners.",
                "label": "deceptive",
                "pattern": "forced-marketing"
            },
            {
                "clause": "We are not responsible for any data breaches or unauthorized access to your information.",
                "label": "deceptive",
                "pattern": "liability-waiver"
            },
            {
                "clause": "Your usage patterns and behavioral data help us improve our services and may be shared with third parties.",
                "label": "deceptive",
                "pattern": "hidden-tracking"
            },
            {
                "clause": "Disputes must be resolved through binding arbitration, waiving your right to jury trial or class action.",
                "label": "deceptive",
                "pattern": "forced-arbitration"
            },
            {
                "clause": "We may transfer your data to any country for processing, regardless of local privacy laws.",
                "label": "deceptive",
                "pattern": "jurisdiction-shopping"
            }
        ]

        return legitimate_clauses + deceptive_clauses

# Initialize dataset
tos_dataset = TOSDataset()
df = pd.DataFrame(tos_dataset.data)

print(f"Dataset created with {len(df)} clauses")
print(f"Distribution:\n{df['label'].value_counts()}")
print("\nSample entries:")
print(df.head())


# Model Loading
"""
### 3. Model Loading
Loading the open-source LLM for evaluation
"""

class LLMEvaluator:
    def __init__(self, model_name="meta-llama/Meta-Llama-3-8B", cache_dir=None):
        """
        Initialize the LLM evaluator
        :param model_name: Name of the LLM model to load
        :param cache_dir: Directory to cache model files
        """
        if cache_dir and not os.path.exists(cache_dir):
            os.makedirs(cache_dir)
            print(f"Created cache directory: {cache_dir}")

        print(f"Loading model: {model_name}")
        if cache_dir:
            print(f"Using cache directory: {cache_dir}")

        self.model_name = model_name
       # self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            cache_dir=cache_dir
        )
        # Add padding token if not present
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        # Load model with appropriate settings for memory efficiency
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            load_in_4bit=True,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="auto" if torch.cuda.is_available() else None,
            low_cpu_mem_usage=True,
            cache_dir=cache_dir
        )

        if not torch.cuda.is_available():
            self.model = self.model.to(device)

        print(f"Model loaded successfully on {device}")

    def generate_prompt(self, clause: str, use_cot: bool = False) -> str:
        """Generate prompt based on CoT setting"""
        if use_cot:
            prompt = f"""Read the following Terms of Service clause carefully and analyze it step by step.

Consider these aspects:
1. Does it contain vague or ambiguous language about data usage?
2. Does it grant excessive rights to the company?
3. Does it limit user rights or legal recourse?
4. Does it allow data sharing without clear consent?
5. Does it have unclear data retention policies?

Think through each aspect, then determine if this clause is deceptive or legitimate.

Clause: "{clause}"

Analysis: Let me think through this step by step.
"""
        else:
            prompt = f"""Determine if the following Terms of Service clause contains deception or privacy violations.

Clause: "{clause}"

Answer (Deceptive/Legitimate):"""

        return prompt

    def evaluate_clause(self, clause: str, use_cot: bool = False, max_length: int = 256) -> Dict:
        """Evaluate a single clause"""
        prompt = self.generate_prompt(clause, use_cot)

        # Tokenize input
        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=512
        ).to(self.model.device)

        # Generate response
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=max_length,
                temperature=0.7,
                do_sample=True,
                top_p=0.95,
                pad_token_id=self.tokenizer.pad_token_id
            )

        # Decode response
        response = self.tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Extract the response after the prompt
        response = response[len(prompt):].strip()

        # Parse the response to determine classification
        classification = self.parse_response(response, use_cot)

        return {
            "prompt": prompt,
            "response": response,
            "classification": classification,
            "use_cot": use_cot
        }

    def parse_response(self, response: str, use_cot: bool) -> str:
        """Parse the model response to extract classification"""
        response_lower = response.lower()

        # Look for keywords indicating deceptive or legitimate
        deceptive_keywords = ['deceptive', 'misleading', 'problematic', 'concerning',
                             'unfair', 'violation', 'privacy violation', 'yes']
        legitimate_keywords = ['legitimate', 'acceptable', 'fair', 'transparent',
                              'reasonable', 'no violation', 'no', 'not deceptive']

        # Count keyword occurrences
        deceptive_score = sum(1 for keyword in deceptive_keywords if keyword in response_lower)
        legitimate_score = sum(1 for keyword in legitimate_keywords if keyword in response_lower)

        # Make decision based on scores
        if deceptive_score > legitimate_score:
            return "deceptive"
        elif legitimate_score > deceptive_score:
            return "legitimate"
        else:
            # If unclear, look for specific phrases
            if "deceptive" in response_lower or "violation" in response_lower:
                return "deceptive"
            elif "legitimate" in response_lower or "not deceptive" in response_lower:
                return "legitimate"
            else:
                return "unclear"
CACHE_PATH = "D:/LLM-offline"
# Initialize evaluator
evaluator = LLMEvaluator(model_name="meta-llama/Meta-Llama-3-8B", cache_dir=CACHE_PATH)  # microsoft/phi-2

# Experiment Execution
"""
### 4. Running the Experiment
Evaluating all clauses with both CoT and non-CoT prompts
"""

class ExperimentRunner:
    def __init__(self, evaluator: LLMEvaluator, dataset: pd.DataFrame):
        self.evaluator = evaluator
        self.dataset = dataset
        self.results = []

    def run_experiment(self):
        """Run the full experiment"""
        print("Starting experiment...")

        for idx, row in tqdm(self.dataset.iterrows(), total=len(self.dataset)):
            clause = row['clause']
            true_label = row['label']

            # Evaluate without CoT
            no_cot_result = self.evaluator.evaluate_clause(clause, use_cot=False)

            # Evaluate with CoT
            cot_result = self.evaluator.evaluate_clause(clause, use_cot=True)

            # Store results
            self.results.append({
                'clause': clause,
                'true_label': true_label,
                'no_cot_prediction': no_cot_result['classification'],
                'no_cot_response': no_cot_result['response'],
                'cot_prediction': cot_result['classification'],
                'cot_response': cot_result['response']
            })

            # Save intermediate results
            if (idx + 1) % 5 == 0:
                self.save_results(f"intermediate_results_{idx+1}.json")

        print("Experiment completed!")
        return pd.DataFrame(self.results)

    def save_results(self, filename: str):
        """Save results to file"""
        with open(filename, 'w') as f:
            json.dump(self.results, f, indent=2)

# Run experiment
experiment = ExperimentRunner(evaluator, df)
results_df = experiment.run_experiment()

# Display sample results
print("\nSample Results:")
results_df[['clause', 'true_label', 'no_cot_prediction', 'cot_prediction']].head()

# Performance Metrics
"""
### 5. Performance Evaluation
Computing accuracy, F1-score, and other metrics
"""

class PerformanceAnalyzer:
    def __init__(self, results_df: pd.DataFrame):
        self.results_df = results_df
        self.metrics = {}

    def calculate_metrics(self):
        """Calculate all performance metrics"""
        # Filter out unclear predictions for metrics calculation
        valid_no_cot = self.results_df[self.results_df['no_cot_prediction'] != 'unclear']
        valid_cot = self.results_df[self.results_df['cot_prediction'] != 'unclear']

        # No-CoT metrics
        if len(valid_no_cot) > 0:
            self.metrics['no_cot'] = {
                'accuracy': accuracy_score(valid_no_cot['true_label'], valid_no_cot['no_cot_prediction']),
                'precision': precision_score(valid_no_cot['true_label'], valid_no_cot['no_cot_prediction'],
                                           pos_label='deceptive', average='binary'),
                'recall': recall_score(valid_no_cot['true_label'], valid_no_cot['no_cot_prediction'],
                                     pos_label='deceptive', average='binary'),
                'f1': f1_score(valid_no_cot['true_label'], valid_no_cot['no_cot_prediction'],
                             pos_label='deceptive', average='binary'),
                'unclear_count': len(self.results_df[self.results_df['no_cot_prediction'] == 'unclear'])
            }

        # CoT metrics
        if len(valid_cot) > 0:
            self.metrics['cot'] = {
                'accuracy': accuracy_score(valid_cot['true_label'], valid_cot['cot_prediction']),
                'precision': precision_score(valid_cot['true_label'], valid_cot['cot_prediction'],
                                           pos_label='deceptive', average='binary'),
                'recall': recall_score(valid_cot['true_label'], valid_cot['cot_prediction'],
                                     pos_label='deceptive', average='binary'),
                'f1': f1_score(valid_cot['true_label'], valid_cot['cot_prediction'],
                             pos_label='deceptive', average='binary'),
                'unclear_count': len(self.results_df[self.results_df['cot_prediction'] == 'unclear'])
            }

        return self.metrics

    def print_metrics(self):
        """Print formatted metrics"""
        print("="*50)
        print("PERFORMANCE METRICS")
        print("="*50)

        for method in ['no_cot', 'cot']:
            if method in self.metrics:
                print(f"\n{method.upper().replace('_', '-')} Performance:")
                print("-"*30)
                for metric, value in self.metrics[method].items():
                    if metric != 'unclear_count':
                        print(f"{metric.capitalize():12s}: {value:.3f}")
                    else:
                        print(f"Unclear predictions: {value}")

        # Calculate improvement
        if 'no_cot' in self.metrics and 'cot' in self.metrics:
            print("\n" + "="*50)
            print("IMPROVEMENT WITH CoT")
            print("="*50)
            for metric in ['accuracy', 'precision', 'recall', 'f1']:
                improvement = self.metrics['cot'][metric] - self.metrics['no_cot'][metric]
                percent_improvement = (improvement / self.metrics['no_cot'][metric]) * 100 if self.metrics['no_cot'][metric] > 0 else 0
                print(f"{metric.capitalize():12s}: {improvement:+.3f} ({percent_improvement:+.1f}%)")

# Calculate metrics
analyzer = PerformanceAnalyzer(results_df)
metrics = analyzer.calculate_metrics()
analyzer.print_metrics()

# Visualizations
"""
### 6. Visualizations
Creating charts to visualize the results
"""

def create_visualizations(results_df: pd.DataFrame, metrics: dict):
    """Create comprehensive visualizations"""

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle('TOS Deception Detection: CoT vs No-CoT Performance', fontsize=16)

    # 1. Accuracy Comparison
    ax1 = axes[0, 0]
    methods = ['No-CoT', 'CoT']
    accuracies = [metrics.get('no_cot', {}).get('accuracy', 0),
                  metrics.get('cot', {}).get('accuracy', 0)]
    bars1 = ax1.bar(methods, accuracies, color=['#FF6B6B', '#4ECDC4'])
    ax1.set_ylabel('Accuracy')
    ax1.set_title('Accuracy Comparison')
    ax1.set_ylim([0, 1])
    for bar, acc in zip(bars1, accuracies):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f'{acc:.2%}', ha='center', va='bottom')

    # 2. F1-Score Comparison
    ax2 = axes[0, 1]
    f1_scores = [metrics.get('no_cot', {}).get('f1', 0),
                 metrics.get('cot', {}).get('f1', 0)]
    bars2 = ax2.bar(methods, f1_scores, color=['#FF6B6B', '#4ECDC4'])
    ax2.set_ylabel('F1-Score')
    ax2.set_title('F1-Score Comparison')
    ax2.set_ylim([0, 1])
    for bar, f1 in zip(bars2, f1_scores):
        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f'{f1:.2%}', ha='center', va='bottom')

    # 3. Precision-Recall Comparison
    ax3 = axes[0, 2]
    x = np.arange(len(methods))
    width = 0.35
    precision_scores = [metrics.get('no_cot', {}).get('precision', 0),
                       metrics.get('cot', {}).get('precision', 0)]
    recall_scores = [metrics.get('no_cot', {}).get('recall', 0),
                    metrics.get('cot', {}).get('recall', 0)]

    bars3 = ax3.bar(x - width/2, precision_scores, width, label='Precision', color='#95E1D3')
    bars4 = ax3.bar(x + width/2, recall_scores, width, label='Recall', color='#F38181')
    ax3.set_ylabel('Score')
    ax3.set_title('Precision vs Recall')
    ax3.set_xticks(x)
    ax3.set_xticklabels(methods)
    ax3.legend()
    ax3.set_ylim([0, 1])

    # 4. Confusion Matrix - No CoT
    ax4 = axes[1, 0]
    valid_no_cot = results_df[results_df['no_cot_prediction'] != 'unclear']
    if len(valid_no_cot) > 0:
        cm_no_cot = confusion_matrix(valid_no_cot['true_label'],
                                     valid_no_cot['no_cot_prediction'],
                                     labels=['legitimate', 'deceptive'])
        sns.heatmap(cm_no_cot, annot=True, fmt='d', cmap='Blues', ax=ax4,
                   xticklabels=['Legitimate', 'Deceptive'],
                   yticklabels=['Legitimate', 'Deceptive'])
        ax4.set_title('Confusion Matrix - No CoT')
        ax4.set_ylabel('True Label')
        ax4.set_xlabel('Predicted Label')

    # 5. Confusion Matrix - CoT
    ax5 = axes[1, 1]
    valid_cot = results_df[results_df['cot_prediction'] != 'unclear']
    if len(valid_cot) > 0:
        cm_cot = confusion_matrix(valid_cot['true_label'],
                                 valid_cot['cot_prediction'],
                                 labels=['legitimate', 'deceptive'])
        sns.heatmap(cm_cot, annot=True, fmt='d', cmap='Greens', ax=ax5,
                   xticklabels=['Legitimate', 'Deceptive'],
                   yticklabels=['Legitimate', 'Deceptive'])
        ax5.set_title('Confusion Matrix - CoT')
        ax5.set_ylabel('True Label')
        ax5.set_xlabel('Predicted Label')

    # 6. Performance Improvement
    ax6 = axes[1, 2]
    metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
    improvements = []
    for metric in ['accuracy', 'precision', 'recall', 'f1']:
        no_cot_val = metrics.get('no_cot', {}).get(metric, 0)
        cot_val = metrics.get('cot', {}).get(metric, 0)
        improvement = ((cot_val - no_cot_val) / no_cot_val * 100) if no_cot_val > 0 else 0
        improvements.append(improvement)

    colors = ['green' if imp > 0 else 'red' for imp in improvements]
    bars6 = ax6.bar(metrics_names, improvements, color=colors, alpha=0.7)
    ax6.set_ylabel('Improvement (%)')
    ax6.set_title('Performance Improvement with CoT')
    ax6.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    ax6.set_xticklabels(metrics_names, rotation=45)

    for bar, imp in zip(bars6, improvements):
        ax6.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                f'{imp:.1f}%', ha='center', va='bottom' if imp > 0 else 'top')

    plt.tight_layout()
    plt.savefig('tos_detection_results.png', dpi=300, bbox_inches='tight')
    plt.show()

# Create visualizations
create_visualizations(results_df, metrics)

# Qualitative Analysis
"""
### 7. Qualitative Analysis
Examining specific examples where CoT made a difference
"""

def analyze_cot_improvements(results_df: pd.DataFrame):
    """Analyze cases where CoT improved classification"""

    # Find cases where CoT was correct but No-CoT was wrong
    improvements = results_df[
        (results_df['cot_prediction'] == results_df['true_label']) &
        (results_df['no_cot_prediction'] != results_df['true_label'])
    ]

    print("="*50)
    print("CASES WHERE CoT IMPROVED CLASSIFICATION")
    print("="*50)

    for idx, row in improvements.head(3).iterrows():
        print(f"\nExample {idx + 1}:")
        print("-"*40)
        print(f"Clause: {row['clause'][:100]}...")
        print(f"True Label: {row['true_label']}")
        print(f"No-CoT Prediction: {row['no_cot_prediction']}")
        print(f"CoT Prediction: {row['cot_prediction']}")
        print(f"\nNo-CoT Response: {row['no_cot_response'][:200]}...")
        print(f"\nCoT Response: {row['cot_response'][:400]}...")
        print("="*50)

    return improvements

improvements_df = analyze_cot_improvements(results_df)

# Error Analysis
"""
### 8. Error Analysis
Analyzing misclassifications and patterns
"""

def error_analysis(results_df: pd.DataFrame):
    """Analyze errors and patterns in misclassifications"""

    # No-CoT errors
    no_cot_errors = results_df[
        (results_df['no_cot_prediction'] != results_df['true_label']) &
        (results_df['no_cot_prediction'] != 'unclear')
    ]

    # CoT errors
    cot_errors = results_df[
        (results_df['cot_prediction'] != results_df['true_label']) &
        (results_df['cot_prediction'] != 'unclear')
    ]

    print("="*50)
    print("ERROR ANALYSIS")
    print("="*50)

    print(f"\nNo-CoT Errors: {len(no_cot_errors)} / {len(results_df)} ({len(no_cot_errors)/len(results_df)*100:.1f}%)")
    print(f"CoT Errors: {len(cot_errors)} / {len(results_df)} ({len(cot_errors)/len(results_df)*100:.1f}%)")

    # Analyze error types
    print("\n" + "-"*40)
    print("ERROR TYPES")
    print("-"*40)

    # False Positives (predicted deceptive but actually legitimate)
    no_cot_fp = no_cot_errors[
        (no_cot_errors['no_cot_prediction'] == 'deceptive') &
        (no_cot_errors['true_label'] == 'legitimate')
    ]
    cot_fp = cot_errors[
        (cot_errors['cot_prediction'] == 'deceptive') &
        (cot_errors['true_label'] == 'legitimate')
    ]

    # False Negatives (predicted legitimate but actually deceptive)
    no_cot_fn = no_cot_errors[
        (no_cot_errors['no_cot_prediction'] == 'legitimate') &
        (no_cot_errors['true_label'] == 'deceptive')
    ]
    cot_fn = cot_errors[
        (cot_errors['cot_prediction'] == 'legitimate') &
        (cot_errors['true_label'] == 'deceptive')
    ]

    print(f"\nFalse Positives (Type I Errors):")
    print(f"  No-CoT: {len(no_cot_fp)}")
    print(f"  CoT: {len(cot_fp)}")

    print(f"\nFalse Negatives (Type II Errors):")
    print(f"  No-CoT: {len(no_cot_fn)}")
    print(f"  CoT: {len(cot_fn)}")

    return {
        'no_cot_errors': no_cot_errors,
        'cot_errors': cot_errors,
        'no_cot_fp': no_cot_fp,
        'cot_fp': cot_fp,
        'no_cot_fn': no_cot_fn,
        'cot_fn': cot_fn
    }

error_results = error_analysis(results_df)

# Response Length Analysis
"""
### 9. Response Length and Quality Analysis
Comparing the verbosity and quality of responses
"""

def response_analysis(results_df: pd.DataFrame):
    """Analyze response characteristics"""

    # Calculate response lengths
    results_df['no_cot_length'] = results_df['no_cot_response'].str.len()
    results_df['cot_length'] = results_df['cot_response'].str.len()

    print("="*50)
    print("RESPONSE CHARACTERISTICS")
    print("="*50)

    print(f"\nAverage Response Length:")
    print(f"  No-CoT: {results_df['no_cot_length'].mean():.0f} characters")
    print(f"  CoT: {results_df['cot_length'].mean():.0f} characters")

    print(f"\nMedian Response Length:")
    print(f"  No-CoT: {results_df['no_cot_length'].median():.0f} characters")
    print(f"  CoT: {results_df['cot_length'].median():.0f} characters")

    # Plot response length distribution
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.hist(results_df['no_cot_length'], bins=20, alpha=0.7, color='#FF6B6B', edgecolor='black')
    ax1.set_xlabel('Response Length (characters)')
    ax1.set_ylabel('Frequency')
    ax1.set_title('No-CoT Response Length Distribution')
    ax1.axvline(results_df['no_cot_length'].mean(), color='red', linestyle='--', label='Mean')
    ax1.legend()

    ax2.hist(results_df['cot_length'], bins=20, alpha=0.7, color='#4ECDC4', edgecolor='black')
    ax2.set_xlabel('Response Length (characters)')
    ax2.set_ylabel('Frequency')
    ax2.set_title('CoT Response Length Distribution')
    ax2.axvline(results_df['cot_length'].mean(), color='teal', linestyle='--', label='Mean')
    ax2.legend()

    plt.tight_layout()
    plt.savefig('response_length_distribution.png', dpi=300, bbox_inches='tight')
    plt.show()

    return results_df

results_df = response_analysis(results_df)

# Export Results
"""
### 10. Export Results and Dataset
Saving all results for future analysis and reproducibility
"""

def export_results(results_df: pd.DataFrame, metrics: dict, dataset: pd.DataFrame):
    """Export all results and data"""

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # 1. Export detailed results
    results_df.to_csv(f'tos_detection_results_{timestamp}.csv', index=False)
    print(f"✓ Results exported to: tos_detection_results_{timestamp}.csv")

    # 2. Export metrics summary
    metrics_df = pd.DataFrame(metrics).T
    metrics_df.to_csv(f'tos_detection_metrics_{timestamp}.csv')
    print(f"✓ Metrics exported to: tos_detection_metrics_{timestamp}.csv")

    # 3. Export original dataset
    dataset.to_csv(f'tos_dataset_{timestamp}.csv', index=False)
    print(f"✓ Dataset exported to: tos_dataset_{timestamp}.csv")

    # 4. Create comprehensive report
    report = {
        'experiment_date': timestamp,
        'model_used': evaluator.model_name,
        'dataset_size': len(dataset),
        'metrics': metrics,
        'summary': {
            'no_cot_accuracy': metrics.get('no_cot', {}).get('accuracy', 0),
            'cot_accuracy': metrics.get('cot', {}).get('accuracy', 0),
            'improvement': metrics.get('cot', {}).get('accuracy', 0) - metrics.get('no_cot', {}).get('accuracy', 0)
        }
    }

    with open(f'tos_detection_report_{timestamp}.json', 'w') as f:
        json.dump(report, f, indent=2)
    print(f"✓ Report exported to: tos_detection_report_{timestamp}.json")

    return timestamp

timestamp = export_results(results_df, metrics, df)

# finalResult

print("="*60)
print("EXPERIMENT SUMMARY")
print("="*60)

print(f"""
Dataset Information:
- Total clauses evaluated: {len(df)}
- Legitimate clauses: {len(df[df['label'] == 'legitimate'])}
- Deceptive clauses: {len(df[df['label'] == 'deceptive'])}

Model Information:
- Model used: {evaluator.model_name}
- Device: {device}

Key Findings:
- No-CoT Accuracy: {metrics.get('no_cot', {}).get('accuracy', 0):.2%}
- CoT Accuracy: {metrics.get('cot', {}).get('accuracy', 0):.2%}
- Accuracy Improvement: {(metrics.get('cot', {}).get('accuracy', 0) - metrics.get('no_cot', {}).get('accuracy', 0)):.2%}

- No-CoT F1-Score: {metrics.get('no_cot', {}).get('f1', 0):.3f}
- CoT F1-Score: {metrics.get('cot', {}).get('f1', 0):.3f}
- F1-Score Improvement: {(metrics.get('cot', {}).get('f1', 0) - metrics.get('no_cot', {}).get('f1', 0)):.3f}

Observations:
1. Chain-of-Thought prompting {'significantly improved' if (metrics.get('cot', {}).get('accuracy', 0) - metrics.get('no_cot', {}).get('accuracy', 0)) > 0.1 else 'moderately improved'} performance
2. CoT responses were approximately {results_df['cot_length'].mean() / results_df['no_cot_length'].mean():.1f}x longer
3. Main improvement areas: {'Precision' if (metrics.get('cot', {}).get('precision', 0) - metrics.get('no_cot', {}).get('precision', 0)) > (metrics.get('cot', {}).get('recall', 0) - metrics.get('no_cot', {}).get('recall', 0)) else 'Recall'}

Files Exported:
- Results: tos_detection_results_{timestamp}.csv
- Metrics: tos_detection_metrics_{timestamp}.csv
- Dataset: tos_dataset_{timestamp}.csv
- Report: tos_detection_report_{timestamp}.json
- Visualizations: tos_detection_results.png, response_length_distribution.png
""")